Repository GSA/sam-styles, pull requests merged in 2019-10, with the labels that each got.

#77 Flip request icon in header secondary nav
  src/components/06-navigation/_nav-secondary.njk
  src/components/07-header/header.config.yml
Labels: Header

#76 IAE-25102 Search bar edit
  src/components/05-form/search.njk
  src/stylesheets/elements/_inputs.scss
Labels: search

#78 Upgrade USWDS version from 2.2.0 to 2.2.1
  package-lock.json
  package.json
Labels: dependencies

#81 fix(patterns): update header and footer
  src/components/patterns/page/page-with-sidebar.njk
Labels: patterns

#80 fix(banner): bugs
  src/stylesheets/components/_banner.scss
  src/stylesheets/theme/_sds-theme-components.scss
Labels: banner

#83 feat(navbar): add navbar component
  src/stylesheets/components/_navbar.scss
  src/stylesheets/theme/_sds-theme-custom-styles.scss
Labels: navbar

#84 refactor(search): start refacotoring of search component
  src/stylesheets/components/_search.scss
  src/stylesheets/theme/_sds-theme-custom-styles.scss
Labels: search

#85 refactor(buttons): initial refactor of button styles
  src/stylesheets/elements/_buttons.scss
Labels: button

#86 Update utilities
  src/stylesheets/theme/_sds-theme-utilities.scss
Labels: utilities

#87 Navbar example
  src/components/patterns/page/page-with-sidebar.njk
Labels: docs

#88 update version to 0.0.35
  package-lock.json
  package.json
Labels: npm release

#91 fix(menu): fix styles for circular buttons
  src/components/13-actions-menu/actions-menu.njk
  src/stylesheets/components/_menu.scss
Labels: menu

#93 feat(icon): add ellipsis icon
  src/icons/icons.js
  src/icons/index.js
  src/icons/sdsEllipsis.js
Labels: icon

#94 feat(button): add shadow class utility
  src/stylesheets/elements/_buttons.scss
Labels: button

#96 Typography fields
  src/components/02-typography/fields.njk
  src/stylesheets/elements/_typography.scss
Labels: typography

#97 feat(button): add small option to sds-button
  src/stylesheets/elements/_buttons.scss
Labels: button

#100 fix: LibSass 3.5.4 inspect() bug
  src/stylesheets/components/_tile.scss
  src/stylesheets/elements/_buttons.scss
Labels: bug

#103 build: update gren configuration
  .grenrc.js
  .grenrc.json
Labels: build

#104 build: add 'breaking change' label
  .grenrc.js
Labels: build

#102 homepage updates
  src/components/icons/icons.njk
  src/icons/icons.js
  src/icons/index.js
  src/icons/sdsPhoto.js
  src/stylesheets/components/_tag.scss
  src/stylesheets/components/_tile.scss
  src/stylesheets/elements/_inputs.scss
Labels: homepage

#105 update version
  package-lock.json
  package.json
Labels: npm release

#106 icons: fix spelling
  src/icons/index.js
Labels: bug

#107 update npm
  package-lock.json
  package.json
Labels: npm release

#109 tile: stacking icon
  src/components/16-tile/tile.njk
  src/stylesheets/components/_tile.scss
Labels: refactor

#110 button: stacking icons in icons button
  src/components/03-buttons/buttons--icon.njk
  src/stylesheets/elements/_buttons.scss
Labels: refactor

#111 icons: add triangle, circle, leaf and pentagon
  src/icons/icons.js
  src/icons/index.js
  src/icons/sdsCircle.js
  src/icons/sdsLeaf.js
  src/icons/sdsPentagon.js
  src/icons/sdsTriangle.js
Labels: feat

#112 search: inverse search refactor
  src/components/05-form/search.njk
  src/stylesheets/elements/_inputs.scss
Labels: refactor

#113 tag: official tag responsive ui
  src/stylesheets/components/_tag.scss
Labels: fix
