Repository GSA/sam-styles, pull requests merged in 2020-10, with the labels that each got.

#347 Added sds-sidenav__label
  src/components/05-patterns/01-pages/pages--page-with-sidebar.njk
  src/stylesheets/components/_sidenav.scss
Labels: fix, patterns

#362 update version
  package-lock.json
  package.json
Labels: npm release

#360 file type button
  src/components/03-components/03-buttons/03-button-icon/button-icon.config.yml
  src/components/03-components/03-buttons/03-button-icon/button-icon.njk
  src/stylesheets/elements/_buttons.scss
Labels: enhancement

#363 update to 0.0.87
  package-lock.json
  package.json
Labels: npm release

#365 fix: angular build issues
  src/stylesheets/components/_buttongroup.scss
  src/stylesheets/elements/_buttons.scss
Labels: fix

#366 update version 0.0.88
  package-lock.json
  package.json
Labels: npm release
