Repository GSA/sam-styles, pull requests merged in 2020-08, with the labels that each got.

#300 Tile
  src/components/03-components/06-dashboard/16-tile/tile--outline.njk
  src/components/03-components/06-dashboard/16-tile/tile.njk
  src/stylesheets/components/_tile.scss
Labels: refactor

#329 Visited links
  src/stylesheets/elements/typography/_links.scss
  src/stylesheets/theme/_sds-theme-color.scss
Labels: enhancement

#340 enhancement(table): updated styling for sds-table
  src/components/03-components/table/table--subsections.njk
  src/components/03-components/table/table.njk
  src/stylesheets/components/_table.scss
Labels: breaking change, enhancement

#338 Re-enabled standard margin class utitlities
  src/stylesheets/theme/_sds-theme-utilities.scss
Labels: bug

#341 update v0.0.81
  package-lock.json
  package.json
Labels: npm release

#339 Icon list
  src/components/01-branding/02-typography/list/list.config.yml
  src/stylesheets/components/_list.scss
Labels: fix

#342 icon--button-lg added
  src/components/03-components/03-buttons/03-button-icon/button-icon.config.yml
  src/components/03-components/03-buttons/03-button-icon/button-icon.njk
  src/stylesheets/elements/_buttons.scss
Labels: enhancement

#343 40147 mfe content page heading margins
  src/components/05-patterns/01-pages/pages--full-page.njk
  src/stylesheets/elements/typography/_misc.scss
Labels: fix

#344 fix(tile): update padding mixin to fix sass compile issue
  src/stylesheets/components/_tile.scss
Labels: fix

#345 npm release: version 0.0.82
  package-lock.json
  package.json
Labels: npm release
