Repository GSA/sam-styles, pull requests merged in 2020-07, with the labels that each got.

#294 Uswds import
  src/components/03-components/cards/cards-demo.config.yml
  src/stylesheets/components/_accordion.scss
  src/stylesheets/components/_card.scss
  src/stylesheets/components/_index.scss
  src/stylesheets/components/_subheader.scss
  src/stylesheets/components/_table.scss
  src/stylesheets/elements/_index.scss
  src/stylesheets/elements/_typography.scss
  src/stylesheets/sam.scss
  src/stylesheets/theme/_sds-theme-custom-styles.scss
  src/stylesheets/theme/_sds-theme-utilities.scss
  src/stylesheets/theme/_styles.scss
  src/stylesheets/theme/styles.scss
Labels: refactor

#301 version update to 0.0.72
  package-lock.json
  package.json
Labels: npm release

#302 footer accordion fix
  src/components/02-structure/02-footer/footer.njk
  src/stylesheets/components/_footer.scss
Labels: fix

#304 update v0.0.73
  package-lock.json
  package.json
Labels: npm release

#303 revert uswds 2.6.0
  package-lock.json
  package.json
Labels: bug

#305 media query fix
  src/stylesheets/components/_seal.scss
Labels: fix

#306 revert uswds back to 2.6.0
  package-lock.json
  package.json
Labels: fix

#307 update v0.0.74
  package-lock.json
  package.json
Labels: npm release

#308 enhancement(list): IAE-38269
  src/components/01-branding/02-typography/list/list.config.yml
  src/components/01-branding/02-typography/list/list.njk
  src/components/01-branding/02-typography/list/readme.md
  src/stylesheets/components/_list.scss
Labels: enhancement

#312 Padding fix
  src/stylesheets/components/_accordion.scss
Labels: fix

#313 version update
  package-lock.json
  package.json
Labels: npm release

#309 refactor(IAE-37766 usa-prose):
  src/components/01-branding/01-colors/color.config.js
  src/components/01-branding/02-typography/_title/title.config.yml
  src/components/01-branding/02-typography/fields.config.js
  src/components/01-branding/02-typography/typesetting.config.js
  src/components/01-branding/02-typography/typography.config.js
  src/components/03-components/03-buttons/03-button-icon/button-icon.config.yml
  src/components/03-components/06-dashboard/dashboard.config.yml
  src/components/04-form-elements/form.config.yml
Labels: refactor

#311 refactor(error-dark): corrected error dark hex code
  src/components/01-branding/01-colors/state-color.njk
  src/components/01-branding/02-typography/paragraph/paragraph.njk
Labels: refactor

#321 update version to 0.0.77
  package-lock.json
  package.json
Labels: npm release

#328 mixed checknox styling
  src/components/04-form-elements/checkboxes.njk
  src/img/minus-white.svg
  src/stylesheets/elements/_inputs.scss
Labels: enhancement

#325 update to v0.0.78
  package-lock.json
  package.json
Labels: npm release

#330 svg reference fix
  src/stylesheets/elements/_inputs.scss
Labels: bug

#331 update v0.0.79
  package-lock.json
  package.json
Labels: npm release
