Repository GSA/sam-styles, pull requests merged in 2020-03, with the labels that each got.

#189 arrow icons added
  src/components/01-branding/03-icons/icons.njk
  src/icons/icons.js
  src/icons/index.js
  src/icons/sdsArrowDown.js
  src/icons/sdsArrowUp.js
Labels: feat

#191 accordion fix for breaking change
  src/stylesheets/components/_accordion.scss
Labels: fix

#192 update version
  package-lock.json
  package.json
Labels: npm release

#190 Add feedback styles to footer
  src/components/02-structure/02-footer/footer.njk
  src/stylesheets/components/_footer.scss
Labels: enhancement

#193 Update sam styles to include new Tile Sample
  src/components/03-components/06-dashboard/16-tile/tile--outline.njk
Labels: chore

#194 feedback component styles
  src/components/02-structure/02-footer/footer.njk
  src/stylesheets/components/_footer.scss
Labels: feat

#199 sds-card--sm
  src/components/03-components/06-dashboard/small.njk
  src/stylesheets/components/_card.scss
Labels: enhancement

#198 sds-card--lg
  src/components/03-components/06-dashboard/large.njk
  src/stylesheets/components/_card.scss
Labels: enhancement

#197 31424 update card style to match cms list design
  src/components/03-components/06-dashboard/card.njk
  src/stylesheets/components/_card.scss
Labels: enhancement

#195 sds-page height fix
  src/stylesheets/components/_page.scss
Labels: feat

#196 forms update
  src/components/04-form-elements/address-form.njk
  src/stylesheets/elements/_inputs.scss
Labels: enhancement

#203 sds card component
  src/components/03-components/06-dashboard/card.njk
  src/components/03-components/06-dashboard/large.njk
  src/components/03-components/06-dashboard/small.njk
  src/components/03-components/08-cards/card-body.njk
  src/components/03-components/08-cards/card-header.njk
  src/components/03-components/08-cards/card-tile.njk
  src/components/03-components/08-cards/card-vertical.njk
  src/components/03-components/08-cards/cards.config.yml
  src/stylesheets/components/_card.scss
Labels: feat

#200 variations of search bar
  src/components/04-form-elements/search.njk
  src/stylesheets/components/_search.scss
  src/stylesheets/elements/_inputs.scss
Labels: enhancement

#204 Update package to version v0.0.55
  package-lock.json
  package.json
Labels: npm release

#201 Added wrapping to chip tags
  src/components/03-components/04-tags/tags--chip.njk
  src/stylesheets/elements/_tags.scss
Labels: enhancement

#208 Fixed size of Article and Note icons
  src/icons/icons.js
  src/icons/sdsArticle.js
  src/icons/sdsNote.js
Labels: bug

#207 designer feedback
  src/stylesheets/components/_card.scss
Labels: feat

#206 designer feedback styles update
  src/components/03-components/09-accordion/accordion.njk
  src/stylesheets/components/_accordion.scss
  src/stylesheets/components/_card.scss
Labels: feat

#209 update version v0.0.56
  package-lock.json
  package.json
Labels: npm release

#212 resetFilter-icon
  src/components/01-branding/03-icons/icons.njk
  src/icons/icons.js
  src/icons/index.js
  src/icons/sdsResetFilter.js
Labels: icon

#205 31053 help results screen
  src/components/01-branding/02-typography/lists.njk
  src/components/05-patterns/02-help-results/help-results.njk
  src/stylesheets/components/_list.scss
  src/stylesheets/elements/_buttons.scss
  src/stylesheets/theme/_sds-theme-custom-styles.scss
Labels: docs, enhancement

#217 sds-search--big fix
  src/stylesheets/components/_search.scss
Labels: fix

#220 Fix Angular Compile Issues
  src/stylesheets/components/_card.scss
  src/stylesheets/components/_footer.scss
  src/stylesheets/components/_page.scss
  src/stylesheets/elements/_tags.scss
Labels: bug

#219 Fix ie bug on out-right-middle popup
  src/components/08-miscellaneous/07-popup/popup.njk
  src/stylesheets/components/_popup.scss
Labels: fix

#221 update version
  package-lock.json
  package.json
Labels: npm release

#223 ie fix
  src/stylesheets/components/_search.scss
Labels: bug

#222 added margin to buttons
  src/stylesheets/elements/_buttons.scss
Labels: enhancement

#215 Added Button Row component
  src/components/03-components/10-buttonrow/README.md
  src/components/03-components/10-buttonrow/buttonrow.config.yml
  src/components/03-components/10-buttonrow/buttonrow.njk
  src/stylesheets/components/_buttonrow.scss
  src/stylesheets/theme/_sds-theme-custom-styles.scss
Labels: feat

#224 added sds-icon-link
  src/components/01-branding/02-typography/links.njk
  src/stylesheets/elements/_links.scss
  src/stylesheets/theme/_sds-theme-custom-styles.scss
Labels: feat

#218 Sds field name value pair
  src/components/01-branding/02-typography/fields.njk
  src/stylesheets/components/_field.scss
  src/stylesheets/theme/_sds-theme-custom-styles.scss
Labels: enhancement
