Repository GSA/sam-styles, pull requests merged in 2020-02, with the labels that each got.

#174 Dual Record- fix. Also refactors name to results-child
  package-lock.json
  src/stylesheets/components/_results.scss
Labels: bug, fix

#169 IAE 30025 status label includes longer words
  package-lock.json
  src/components/03-components/04-labels/labels--outline.njk
  src/stylesheets/elements/_tags.scss
Labels: enhancement

#179 organized folders
  src/components/04-form-elements/address-form.njk
  src/components/04-form-elements/dropdown.njk
  src/components/04-form-elements/form.config.yml
  src/components/04-form-elements/name-form.njk
  src/components/04-form-elements/search.njk
  src/components/04-form-elements/text-input.njk
  src/components/05-patterns/01-page/page-with-sidebar.njk
  src/components/05-patterns/layouts.config.yml
  src/components/06-miscellaneous/01-navigation/_nav-primary.njk
  src/components/06-miscellaneous/01-navigation/_nav-secondary.njk
  src/components/06-miscellaneous/01-navigation/nav-primary.config.yml
  src/components/06-miscellaneous/01-navigation/nav-secondary.config.yml
  src/components/06-miscellaneous/01-navigation/navigation.config.yml
  src/components/06-miscellaneous/02-sort/sort.config.yml
  src/components/06-miscellaneous/02-sort/sort.njk
  src/components/06-miscellaneous/03-toolbar/toolbar.config.js
  src/components/06-miscellaneous/03-toolbar/toolbar.njk
  src/components/14-alerts/alerts--header.njk
  src/components/14-alerts/alerts.config.yml
Labels: feat

#177 Sidenav gray updated to new palette
  src/stylesheets/components/_sidenav.scss
Labels: fix

#175 Replaced gray color palette
  src/components/01-branding/01-colors/theme-color.njk
  src/stylesheets/theme/_sds-theme-color.scss
Labels: feat

#178 refactor status
  src/components/03-components/04-labels/labels--outline.njk
  src/components/03-components/04-labels/labels--status.njk
  src/components/03-components/04-tags/tags--chip.njk
  src/components/03-components/04-tags/tags--outline-sam.njk
  src/components/03-components/04-tags/tags--outline.njk
  src/components/03-components/04-tags/tags--status.njk
  src/components/03-components/04-tags/tags.config.yml
  src/components/03-components/04-tags/tags.njk
  src/stylesheets/elements/_tags.scss
Labels: breaking change, refactor

#181 Update _tags.scss Added border definition
  src/stylesheets/elements/_tags.scss
Labels: bug

#156 29173 popup
  src/components/08-miscellaneous/07-popup/popup.config.yml
  src/components/08-miscellaneous/07-popup/popup.njk
  src/icons/sdsNewVersion.js
  src/stylesheets/components/_popup.scss
  src/stylesheets/theme/_sds-theme-custom-styles.scss
Labels: feat

#183 version bump v0.0.52
  package-lock.json
  package.json
Labels: npm release

#182 tile styles updated to match new designs
  src/stylesheets/components/_tile.scss
Labels: enhancement

#188 update package to 0.0.53
  package-lock.json
  package.json
Labels: npm release

#187 sds accordion styles
  src/components/03-components/09-accordion/accordion.njk
  src/stylesheets/components/_accordion.scss
Labels: feat
