Repository GSA/sam-styles, pull requests merged in 2020-05, with the labels that each got.

#254 update v0.0.65
  package-lock.json
  package.json
Labels: npm release

#256 search styles
  src/stylesheets/components/_search.scss
Labels: fix

#257 update v0.0.66
  package-lock.json
  package.json
Labels: npm release

#236 P2 31048 filtering by domain
  src/components/06-miscellaneous/03-toolbar/toolbar.njk
  src/stylesheets/components/_accordion.scss
  src/stylesheets/components/_toolbar.scss
Labels: breaking change, enhancement

#241 Footer modifications
  src/components/02-structure/02-footer/footer.config.js
  src/components/02-structure/02-footer/footer.njk
  src/stylesheets/components/_footer.scss
Labels: Footer

#262 Iae 34767/icons
  docs/02-for-developers/04-icons.md
  src/components/01-branding/02-typography/links.njk
  src/components/01-branding/03-icons/README.md
  src/components/01-branding/03-icons/_icons--single.njk
  src/components/01-branding/03-icons/icons.config.yml
  src/components/01-branding/03-icons/icons.njk
  src/components/01-branding/04-list/list.config.yml
  src/components/01-branding/04-list/list.njk
  src/components/01-branding/icon/README.md
  src/components/01-branding/icon/icon.config.js
  src/components/01-branding/icon/icon.njk
  src/components/02-structure/01-header/header.config.yml
  src/components/02-structure/02-footer/footer.njk
  src/components/02-structure/04-seal/seal.config.yml
  src/components/02-structure/04-seal/seal.njk
  src/components/03-components/01-actions/_actions--single.njk
  src/components/03-components/01-actions/actions.config.yml
  src/components/03-components/01-actions/actions.njk
  src/components/03-components/02-alerts/alerts--block.njk
  src/components/03-components/02-alerts/alerts--expanded.njk
  src/components/03-components/02-alerts/alerts--header.njk
  src/components/03-components/02-alerts/alerts.config.yml
  src/components/03-components/02-alerts/alerts.njk
  src/components/03-components/03-buttons/buttons--icon.njk
  src/components/03-components/03-buttons/buttons.njk
  src/components/03-components/06-dashboard/16-tile/tile--outline.njk
  src/components/03-components/06-dashboard/16-tile/tile.njk
  src/components/03-components/08-card/card--vertical.njk
  src/components/03-components/08-card/card.config.yml
  src/components/03-components/08-card/card.njk
  src/components/03-components/10-buttonrow/buttonrow.njk
  src/components/05-patterns/01-pages/help-results.njk
  src/components/05-patterns/01-pages/landing-page.njk
  src/components/05-patterns/01-pages/page-with-sidebar.njk
  src/components/05-patterns/01-pages/pages.config.yml
  src/components/06-miscellaneous/01-navigation/_nav-primary.njk
  src/components/06-miscellaneous/01-navigation/_nav-secondary.njk
  src/components/06-miscellaneous/07-popup/popup.config.yml
  src/components/06-miscellaneous/07-popup/popup.njk
  src/components/site-title/site-title.njk
  src/icons/icons.js
Labels: refactor
