Repository GSA/sam-styles, pull requests merged in 2020-01, with the labels that each got.

#146 sds-tile
  src/components/03-components/06-dashboard/16-tile/tile--outline.njk
  src/stylesheets/components/_tile.scss
Labels: feat

#147 Icon button
  src/stylesheets/elements/_buttons.scss
Labels: feat

#148 typo
  src/components/03-components/06-dashboard/16-tile/tile--outline.njk
Labels: feat

#151 icon-button
  src/components/03-components/03-buttons/buttons--icon.njk
  src/stylesheets/elements/_buttons.scss
Labels: feat

#149 Seal
  src/components/02-structure/04-seal/seal.config.yml
  src/components/02-structure/04-seal/seal.njk
  src/components/08-miscellaneous/01-form/dropdown.njk
  src/components/08-miscellaneous/01-form/form.config.yml
  src/components/08-miscellaneous/01-form/text-input.njk
  src/components/08-miscellaneous/01-tag/tag.njk
  src/components/08-miscellaneous/02-navigation/_nav-primary.njk
  src/components/08-miscellaneous/02-navigation/_nav-secondary.njk
  src/components/08-miscellaneous/02-navigation/nav-primary.config.yml
  src/components/08-miscellaneous/02-navigation/nav-secondary.config.yml
  src/components/08-miscellaneous/02-navigation/navigation.config.yml
  src/components/08-miscellaneous/03-form/address-form.njk
  src/components/08-miscellaneous/03-form/name-form.njk
  src/components/08-miscellaneous/04-sort/sort.config.yml
  src/components/08-miscellaneous/04-sort/sort.njk
  src/components/08-miscellaneous/05-toolbar/toolbar.config.js
  src/components/08-miscellaneous/05-toolbar/toolbar.njk
  src/stylesheets/components/_seal.scss
  src/stylesheets/components/_tag.scss
  src/stylesheets/theme/_sds-theme-custom-styles.scss
Labels: feat

#153 Add IE11 fix for input line height
  src/stylesheets/elements/_typography.scss
Labels: bug

#158 update to version v0.0.46
  package-lock.json
  package.json
Labels: npm release

#152 styles update for homepage
  src/components/03-components/06-dashboard/16-tile/tile--outline.njk
  src/stylesheets/components/_event.scss
  src/stylesheets/components/_seal.scss
  src/stylesheets/components/_tile.scss
  src/stylesheets/elements/_buttons.scss
  src/stylesheets/elements/_inputs.scss
Labels: feat

#161 update to v0.0.47
  package-lock.json
  package.json
Labels: npm release

#160 added class to prevent conflicts with existing accordion implementations
  src/components/03-components/09-accordion/accordion.njk
  src/stylesheets/theme/_sds-theme-custom-styles.scss
Labels: bug

#163 Tile styles update
  src/stylesheets/components/_seal.scss
  src/stylesheets/components/_tile.scss
Labels: feat

#171 Update to allowed USWDS value (integer vs string)
  src/stylesheets/components/_seal.scss
Labels: bug

#170 Information circle icon clean
  package-lock.json
  src/components/01-branding/03-icons/icons.njk
  src/icons/icons.js
  src/icons/index.js
  src/icons/sdsInformationCircle.js
Labels: enhancement

#173 update v 0.0.50
  package-lock.json
  package.json
Labels: npm release
