Repository GSA/sam-styles, pull requests merged in 2020-06, with the labels that each got.

#280 IAE-36320/icons
  src/components/01-branding/icon/README.md
  src/components/01-branding/icons/icon/icon.config.js
  src/components/01-branding/icons/icon/icon.njk
  src/components/01-branding/icons/icon/readme.md
  src/components/01-branding/icons/layered-icon/_preview.njk
  src/components/01-branding/icons/layered-icon/layered-icon.config.js
  src/components/01-branding/icons/layered-icon/layered-icon.njk
  src/components/01-branding/icons/layered-icon/readme.md
  src/components/03-components/01-actions/actions.config.yml
  src/components/03-components/01-actions/actions.njk
  src/components/03-components/03-buttons/buttons--icon.njk
  src/components/03-components/03-buttons/buttons.config.yml
  src/components/03-components/06-dashboard/16-tile/tile--outline.njk
  src/components/03-components/06-dashboard/16-tile/tile.config.yml
  src/components/03-components/06-dashboard/16-tile/tile.njk
  src/components/05-patterns/01-pages/pages--page-with-sidebar.njk
  src/components/05-patterns/01-pages/pages.config.yml
  src/components/05-patterns/01-pages/pages.njk
  src/components/06-miscellaneous/01-navigation/_nav-primary.njk
  src/components/06-miscellaneous/01-navigation/nav-primary.config.yml
  src/stylesheets/theme/_sds-theme-utilities.scss
Labels: enhancement

#277 Iae 35523/cards
  fractal.js
  src/components/01-branding/02-typography/_title/title.config.yml
  src/components/01-branding/02-typography/_title/title.njk
  src/components/01-branding/02-typography/list/list.njk
  src/components/03-components/08-card/card--vertical.njk
  src/components/03-components/08-card/card.config.yml
  src/components/03-components/08-card/card.njk
  src/components/03-components/cards/_card.njk
  src/components/03-components/cards/card--vertical.njk
  src/components/03-components/cards/card.config.yml
  src/components/03-components/cards/cards-demo--vertical.njk
  src/components/03-components/cards/cards-demo.config.yml
  src/components/03-components/cards/cards-demo.njk
  src/components/05-patterns/01-pages/pages.config.yml
  src/components/05-patterns/01-pages/pages.njk
  src/stylesheets/components/_card.scss
Labels: enhancement

#281 updated uswds version
  package-lock.json
  package.json
Labels: feat

#282 Iae 36666/link list
  fractal.js
  src/components/01-branding/02-typography/_link/_link.njk
  src/components/01-branding/02-typography/_link/link.config.yml
  src/components/01-branding/02-typography/list/list.config.yml
  src/components/01-branding/02-typography/list/list.njk
  src/components/01-branding/02-typography/list/readme.md
  src/components/02-structure/02-footer/footer.config.js
  src/components/05-patterns/01-pages/pages.config.yml
  src/stylesheets/components/_list.scss
Labels: breaking change, enhancement

#285 form validation
  src/stylesheets/elements/_inputs.scss
Labels: feat

#265 Accordion
  src/components/03-components/09-accordion/accordion.config.js
  src/components/03-components/09-accordion/accordion.config.yml
  src/components/03-components/09-accordion/accordion.njk
  src/components/05-patterns/01-pages/pages.njk
  src/stylesheets/components/_accordion.scss
  src/stylesheets/components/_toolbar.scss
Labels: feat

#289 focus update
  src/stylesheets/components/_accordion.scss
Labels: feat

#288 px switched to rem
  src/stylesheets/elements/_inputs.scss
Labels: fix

#291 updated to v0.0.71
  package-lock.json
  package.json
Labels: npm release

#290 New layout samples
  src/components/03-components/cards/card.config.yml
  src/components/05-patterns/01-pages/pages--full-page.njk
  src/components/05-patterns/01-pages/pages--help-results.njk
  src/components/05-patterns/01-pages/pages--landing-page.njk
  src/components/05-patterns/01-pages/pages--left-aside.njk
  src/components/05-patterns/01-pages/pages--page-with-sidebar.njk
  src/components/05-patterns/01-pages/pages--right-aside.njk
  src/components/05-patterns/01-pages/pages--three-columns.njk
  src/components/05-patterns/01-pages/pages.config.yml
  src/components/05-patterns/01-pages/pages.njk
Labels: enhancement

#292 Iae 37360/table
  src/components/03-components/table/readme.md
  src/components/03-components/table/table--subsections.njk
  src/components/03-components/table/table.config.yml
  src/components/03-components/table/table.njk
  src/stylesheets/components/_table.scss
Labels: enhancement

#293 enhancement(table-stripes)
  src/stylesheets/components/_table.scss
Labels: enhancement
