Repository GSA/sam-styles, pull requests merged in 2021-03, with the labels that each got.

#426 Add slideout sheet
  src/stylesheets/components/_index.scss
  src/stylesheets/components/_slideout.scss
Labels: enhancement

#434 Uswds components
  src/components/03-components/14-collection/collection--calendar.njk
  src/components/03-components/14-collection/collection--condensed.njk
  src/components/03-components/14-collection/collection--media.njk
  src/components/03-components/14-collection/collection.config.yml
  src/components/03-components/14-collection/collection.njk
  src/components/03-components/14-processlist/processlist.config.yml
  src/components/03-components/14-processlist/processlist.njk
  src/components/03-components/15-stepindicator/stepindicator--centered.njk
  src/components/03-components/15-stepindicator/stepindicator--counter.njk
  src/components/03-components/15-stepindicator/stepindicator--no-labels.njk
  src/components/03-components/15-stepindicator/stepindicator--small.njk
  src/components/03-components/15-stepindicator/stepindicator.config.yml
  src/components/03-components/15-stepindicator/stepindicator.njk
  src/components/03-components/16-summary/summary.config.yml
  src/components/03-components/16-summary/summary.njk
Labels: feat

#436 change styling for the step indicator
  src/components/03-components/14-collection/collection.config.yml
  src/components/03-components/15-stepindicator/stepindicator--counters.njk
  src/stylesheets/components/_index.scss
  src/stylesheets/components/_stepindicator.scss
Labels: feat

#438 secondary-nav hover
  src/stylesheets/components/_navigation.scss
Labels: fix

#439 update version to 0.0.106
  package-lock.json
  package.json
Labels: npm release
