Repository GSA/sam-styles, pull requests merged in 2021-01, with the labels that each got.

#397 Remove overflow auto in system alerts container
  src/stylesheets/components/_alert.scss
Labels: bug

#401 Use numbers instead of strings for margins and padding in header.scss
  src/stylesheets/components/_header.scss
Labels: bug

#400 V0.0.96
  package-lock.json
  package.json
Labels: docs

#402 select issue fix
  src/stylesheets/components/_search.scss
Labels: fix

#403 Toolbar IE fix
  src/stylesheets/components/_toolbar.scss
Labels: fix

#408 icon list fix
  src/stylesheets/components/_list.scss
Labels: fix

#406 Fixed autocomplete overflow. Fixed border not showing in toolbar.
  src/stylesheets/components/_toolbar.scss
Labels: fix
